name: ultrasound_pc

task_name: pc

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
        shape: [1024, 3]
        type: point_cloud
    img:
        shape: *image_shape
        type: rgb
    state:
      shape: [18]
      type: low_dim
    force:
      shape: [6]
      type: low_dim
  action:
    shape: [12] #state + force

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.ultrasound_dataset.UltrasoundPCDataset
  zarr_path: data/ultrasound_data_pc.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
